"""rename_stop_loss_percent_to_percentage

Revision ID: 02b7d24ed1f1
Revises: b07f1ec2ff54
Create Date: 2025-06-22 11:49:34.917275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b7d24ed1f1'
down_revision: Union[str, Sequence[str], None] = 'b07f1ec2ff54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'stop_loss_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('stop_loss_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
