"""add stop loss retry tracking fields to Trade model

Revision ID: 4c1243da0136
Revises: c7f8db0e214a
Create Date: 2025-06-27 20:55:29.753924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1243da0136'
down_revision: Union[str, Sequence[str], None] = 'c7f8db0e214a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stop_loss_retry_count', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('stop_loss_last_attempt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trades', sa.Column('stop_loss_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'stop_loss_failed')
    op.drop_column('trades', 'stop_loss_last_attempt')
    op.drop_column('trades', 'stop_loss_retry_count')
    # ### end Alembic commands ###
