"""add stop_loss column to trades

Revision ID: 591a6d0e1cb0
Revises: f5f0e0d3a25b
Create Date: 2025-06-28 00:00:19.219717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591a6d0e1cb0'
down_revision: Union[str, Sequence[str], None] = 'f5f0e0d3a25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stop_loss', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'stop_loss')
    # ### end Alembic commands ###
