"""Add strategy_params to bot

Revision ID: 7000d7bcb1f
Revises: f5f0e0d3a25b
Create Date: 2025-06-30 21:33:28.443901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7000d7bcb1f'
down_revision: Union[str, Sequence[str], None] = 'f5f0e0d3a25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add strategy_params JSONB column to bots table for future strategy timeframe flexibility."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('strategy_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove strategy_params column from bots table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'strategy_params')
    # ### end Alembic commands ### 