"""add_client_order_id_to_trades

Revision ID: 7ee431d863ab
Revises: 60557ca5ea95
Create Date: 2025-06-28 23:55:15.434163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee431d863ab'
down_revision: Union[str, Sequence[str], None] = '60557ca5ea95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cassava_trend_data_id'), 'cassava_trend_data', ['id'], unique=False)
    op.add_column('trades', sa.Column('client_order_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'client_order_id')
    op.drop_index(op.f('ix_cassava_trend_data_id'), table_name='cassava_trend_data')
    # ### end Alembic commands ###
