"""add exchange_info and error_message to Trade model

Revision ID: af2c581f59df
Revises: 4c1243da0136
Create Date: 2025-06-27 21:41:31.876895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2c581f59df'
down_revision: Union[str, Sequence[str], None] = '4c1243da0136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('exchange_info', sa.Text(), nullable=True))
    op.add_column('trades', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'error_message')
    op.drop_column('trades', 'exchange_info')
    # ### end Alembic commands ###
