"""add_trading_limits_to_bot

Revision ID: b21e73b30f91
Revises: bb48332e9441
Create Date: 2025-06-22 10:44:46.328020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21e73b30f91'
down_revision: Union[str, Sequence[str], None] = 'bb48332e9441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('max_trades_per_day', sa.Integer(), nullable=True))
    op.add_column('bots', sa.Column('min_balance_threshold', sa.Float(), nullable=True))
    op.add_column('bots', sa.Column('max_daily_loss', sa.Float(), nullable=True))
    op.add_column('bots', sa.Column('max_position_size_percent', sa.Float(), nullable=True))
    op.add_column('bots', sa.Column('trade_interval_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'trade_interval_seconds')
    op.drop_column('bots', 'max_position_size_percent')
    op.drop_column('bots', 'max_daily_loss')
    op.drop_column('bots', 'min_balance_threshold')
    op.drop_column('bots', 'max_trades_per_day')
    # ### end Alembic commands ###
