"""add celery_task_id to bot model

Revision ID: bb48332e9441
Revises: d0526606ec2e
Create Date: 2025-06-22 09:07:44.703193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb48332e9441'
down_revision: Union[str, Sequence[str], None] = 'd0526606ec2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'celery_task_id')
    # ### end Alembic commands ###
