"""add_exchange_order_id_to_positions

Revision ID: c7f8db0e214a
Revises: f19214719fd6
Create Date: 2025-06-26 22:33:11.631051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f8db0e214a'
down_revision: Union[str, Sequence[str], None] = 'f19214719fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('exchange_order_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'exchange_order_id')
    # ### end Alembic commands ###
