"""add exchange connection to bot

Revision ID: d0526606ec2e
Revises: 
Create Date: 2025-06-22 08:34:24.595442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0526606ec2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('exchange_connection_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bots', 'exchange_connections', ['exchange_connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_column('bots', 'exchange_connection_id')
    # ### end Alembic commands ###
