"""add_bot_id_and_pnl_to_activity

Revision ID: e2a2e2ffed89
Revises: 02b7d24ed1f1
Create Date: 2025-06-22 12:10:52.439885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2a2e2ffed89'
down_revision: Union[str, Sequence[str], None] = '02b7d24ed1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('pnl', sa.Float(), nullable=True))
    op.alter_column('activities', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activities', 'type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('activities', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_activities_bot_id'), 'activities', ['bot_id'], unique=False)
    op.create_index(op.f('ix_activities_type'), 'activities', ['type'], unique=False)
    op.create_foreign_key(None, 'activities', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_index(op.f('ix_activities_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_bot_id'), table_name='activities')
    op.alter_column('activities', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('activities', 'type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('activities', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('activities', 'pnl')
    op.drop_column('activities', 'bot_id')
    # ### end Alembic commands ###
