"""add stop-limit order type to constraint

Revision ID: f5f0e0d3a25b
Revises: af2c581f59df
Create Date: 2025-06-27 23:37:16.993070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f0e0d3a25b'
down_revision: Union[str, Sequence[str], None] = 'af2c581f59df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
